version: '3.5'

services:
  db:
    image: postgres:14-alpine
    command: postgres -c 'max_connections=200'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=a1501s0607
      - POSTGRES_DB=schooldiary
    volumes:
      - pg_data:/varlib/postgresql/data

volumes:
  pg_data: